<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LocationVehicule"
    nsURI="http://locationVehicule/1.0" nsPrefix="locationVehicule">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Personne">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nomPasVide identifiantUnique prenomPasVide"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nomPasVide" value="nom.size() > 0"/>
      <details key="identifiantUnique" value="Personne.allInstances()->isUnique(personne : Personne | personne.identifiant)"/>
      <details key="prenomPasVide" value="prenom.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agitCommeClient" ordered="false"
        eType="#//Client" volatile="true" derived="true" containment="true" eOpposite="#//Client/est"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prenom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domicile" ordered="false"
        lowerBound="1" eType="#//Localisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estEmploye" eType="#//EmployeAgence"
        eOpposite="#//EmployeAgence/est"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uneSeuleVoitureLouee"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uneSeuleVoitureLouee" value="let loc : Bag(Location) = execute->select(t : Transaction | t.oclIsTypeOf(Location)) in loc->iterate(locElem : Location ; locationUnique : Bag(Location) = Bag{} | locationUnique->includesAll(loc->select(l : Location | l.datePrevueDuRetour._'>='(locElem.datePrevueDuRetour) and l.datePrevueDuRetour._'&lt;='(locElem.dateTransaction))))->size() &lt;= 1"/>
    </eAnnotations>
    <eOperations name="listeMauvaisesExperiences" eType="#//MauvaiseExperience"/>
    <eOperations name="listeTransactions" eType="#//Transaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="possede" upperBound="-1"
        eType="#//Reservation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loue" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="execute" upperBound="-1"
        eType="#//Transaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="est" lowerBound="1" eType="#//Personne"
        eOpposite="#//Personne/agitCommeClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reservation" eSuperTypes="#//Transaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="statutTermine periodeLocation dateTransaction"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="statutTermine" value="if self.faiteEnVueDe &lt;> null then statut = 1 else statut &lt;> 1 endif"/>
      <details key="periodeLocation" value="dateFin._'>'(self.dateDebut)"/>
      <details key="dateTransaction" value="self.dateTransaction._'&lt;'(self.dateDebut)"/>
    </eAnnotations>
    <eOperations name="getDuree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eOperations name="assigneVoitureJourneeSuivante" ordered="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.assigne = Bag{voiture}"/>
        <details key="pre_estBonneCategorie" value="voiture.estDeCategorie = categorie"/>
        <details key="post_estAssigee" value="self.assigne &lt;> null"/>
        <details key="pre_estPasAssigee" value="self.assigne = null"/>
      </eAnnotations>
      <eParameters name="voiture" ordered="false" eType="#//Voiture"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Refere" lowerBound="1"
        eType="#//Voiture"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateDebut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorie" eType="#//Categorie"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faiteEnVueDe" eType="#//Location"
        eOpposite="#//Location/faiteApartirDe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estFourniePar" lowerBound="1"
        eType="#//AgenceReservation" eOpposite="#//AgenceReservation/fournit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demandeePour" lowerBound="1"
        eType="#//Categorie" eOpposite="#//Categorie/demande"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aVoitureAssignee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refuseePourMauvaisesExperiences"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Voiture">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="identifiantUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="identifiantUnique" value="Voiture.allInstances()->isUnique(voiture : Voiture | voiture.identifiant)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estDeCategorie" lowerBound="1"
        eType="#//Categorie" eOpposite="#//Categorie/categoriseVoiture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estAssigne" eType="#//Reservation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estAssigneeA" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/assigne"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enReparation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agence">
    <eOperations name="identifieBesoinsSupplementaires">
      <eParameters name="dateDuJour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eOperations name="nbVoituresReservees" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.aRoleFournisseur.fournit->select(reservation : Reservation | reservation.statut = 0)->size()"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="nbVoituresReservees" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.aRoleFournisseur.fournit->select(reservation : Reservation | reservation.statut = 0 and reservation.categorie = categorie)->size()"/>
      </eAnnotations>
      <eParameters name="categorie" eType="#//Categorie"/>
    </eOperations>
    <eOperations name="nombreDeVoitures" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.aEnInventaire->select(voiture : Voiture | voiture.estDeCategorie = categorie)->size()"/>
      </eAnnotations>
      <eParameters name="categorie" eType="#//Categorie"/>
    </eOperations>
    <eOperations name="demanderTransfert" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.nbVoituresReservees(categorie) > nombreDeVoitures(categorie)"/>
      </eAnnotations>
      <eParameters name="categorie" eType="#//Categorie"/>
    </eOperations>
    <eOperations name="locationsNonRetournees" ordered="false" eType="#//Location">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.aRoleLocateur.loue->select(location : Location | location.datePrevueDuRetour._'&lt;'(today) and location.statut = 0)"/>
      </eAnnotations>
      <eParameters name="today" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aEnInventaire" upperBound="-1"
        eType="#//Voiture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estDirigeePar" lowerBound="1"
        eType="#//Gestionnaire" containment="true" eOpposite="#//Gestionnaire/dirige"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seSitue" ordered="false"
        lowerBound="1" eType="#//Localisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aRoleFournisseur" eType="#//AgenceReservation"
        eOpposite="#//AgenceReservation/fournisseurEstJouePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aRoleLocateur" eType="#//AgenceLocation"
        eOpposite="#//AgenceLocation/locateurEstJouePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aRoleRecepteur" eType="#//AgenceRetour"
        eOpposite="#//AgenceRetour/recepteurEstJouePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effectue" eType="#//AgenceTransfert"
        eOpposite="#//AgenceTransfert/transfertJouePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estSupporteePar" upperBound="-1"
        eType="#//Commis" containment="true" eOpposite="#//Commis/travailPour"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commis" eSuperTypes="#//EmployeAgence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="travailPour" lowerBound="1"
        eType="#//Agence" eOpposite="#//Agence/estSupporteePar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gestionnaire" eSuperTypes="#//EmployeAgence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dirige" lowerBound="1"
        eType="#//Agence" eOpposite="#//Agence/estDirigeePar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//Transaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="periodeLocation locationImmediate statutTermine"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="periodeLocation" value="datePrevueDuRetour._'>'(self.dateTransaction)"/>
      <details key="locationImmediate" value="immediate = self.faiteApartirDe = null"/>
      <details key="statutTermine" value="if self.produit &lt;> null then statut = 1 else statut &lt;> 1 endif"/>
    </eAnnotations>
    <eOperations name="getDuree" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datePrevueDuRetour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produit" eType="#//Retour"
        eOpposite="#//Retour/estLeProduitDe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faiteApartirDe" eType="#//Reservation"
        eOpposite="#//Reservation/faiteEnVueDe"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="immediate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estLoueePar" lowerBound="1"
        eType="#//AgenceLocation" eOpposite="#//AgenceLocation/loue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Categorie">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="identifiantUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="identifiantUnique" value="Categorie.allInstances()->isUnique(categorie : Categorie | categorie.nom)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demande" upperBound="-1"
        eType="#//Reservation" eOpposite="#//Reservation/demandeePour"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categoriseVoiture" upperBound="-1"
        eType="#//Voiture" eOpposite="#//Voiture/estDeCategorie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MauvaiseExperience">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relate" lowerBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Detail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seRapporteA" lowerBound="1"
        eType="#//Transaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Localisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adresseCivique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ville" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telephone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmployeAgence" abstract="true">
    <eOperations name="assigneVoitureAReservation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traite" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/estTraiteePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="est" eType="#//Personne"
        containment="true" eOpposite="#//Personne/estEmploye"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Retour" eSuperTypes="#//Transaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="statutTermine"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="statutTermine" value="statut = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estLeProduitDe" eType="#//Location"
        eOpposite="#//Location/produit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estRecuePar" lowerBound="1"
        eType="#//AgenceRetour" eOpposite="#//AgenceRetour/recoit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voitureEnBonneCondition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="montantPaye" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgenceReservation">
    <eOperations name="enregistre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fournit" upperBound="-1"
        eType="#//Reservation" eOpposite="#//Reservation/estFourniePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fournisseurEstJouePar"
        lowerBound="1" eType="#//Agence" eOpposite="#//Agence/aRoleFournisseur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgenceLocation">
    <eOperations name="loueVoiture" ordered="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="pre_aVoiture" value="self.locateurEstJouePar.aEnInventaire->size() > 0"/>
        <details key="post_uneVoituredeMoins" value="self.locateurEstJouePar.aEnInventaire->size() = self.locateurEstJouePar.aEnInventaire->size() - 1"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loue" upperBound="-1" eType="#//Location"
        eOpposite="#//Location/estLoueePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locateurEstJouePar" lowerBound="1"
        eType="#//Agence" eOpposite="#//Agence/aRoleLocateur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgenceRetour">
    <eOperations name="recoitVoiture" ordered="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="post_uneVoituredePlus" value="self.recepteurEstJouePar.aEnInventaire->size() = self.recepteurEstJouePar.aEnInventaire->size() + 1"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recoit" upperBound="-1"
        eType="#//Retour" eOpposite="#//Retour/estRecuePar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recepteurEstJouePar" lowerBound="1"
        eType="#//Agence" eOpposite="#//Agence/aRoleRecepteur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AgenceTransfert">
    <eOperations name="transfereVoiture" ordered="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="post_transfertUneVoituredeMoins" value="self.transfertJouePar.aEnInventaire->size() = self.transfertJouePar.aEnInventaire->size() - 1"/>
        <details key="post_transfertUneVoituredePlus" value="agence.aEnInventaire->size() = agence.aEnInventaire->size() + 1"/>
        <details key="pre_transfertAVoiture" value="self.transfertJouePar.aEnInventaire->size() > 0"/>
      </eAnnotations>
      <eParameters name="voiture" eType="#//Voiture"/>
      <eParameters name="agence" eType="#//Agence"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfereDe" upperBound="-1"
        eType="#//Transfert"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfertJouePar" lowerBound="1"
        eType="#//Agence" eOpposite="#//Agence/effectue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="estTraiteePar" lowerBound="1"
        eType="#//EmployeAgence" eOpposite="#//EmployeAgence/traite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTransaction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigne" eType="#//Voiture"
        eOpposite="#//Voiture/estAssigneeA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statut" eType="#//Statut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transfert">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objetDuTransfert" lowerBound="1"
        eType="#//Voiture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="de" eType="#//Agence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transfereVers" lowerBound="1"
        eType="#//Agence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Statut">
    <eLiterals name="EnCours"/>
    <eLiterals name="Terminee" value="1"/>
    <eLiterals name="Annulee" value="2"/>
  </eClassifiers>
</ecore:EPackage>
