<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LocationVéhicule"
    nsURI="http://defaultname/1.0" nsPrefix="locationVehicule">
  <eClassifiers xsi:type="ecore:EClass" name="Personne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joue le role" eType="#//Client"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Commis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//Gestionnaire"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prénom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eOperations name="réserveVéhicule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Possède" upperBound="-1"
        eType="#//Réservation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loue" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Dossier%20Client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Réservation">
    <eOperations name="getPériodeLocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Réfère" lowerBound="1"
        eType="#//Voiture"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateDébut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catégorie" eType="#//Catégorie"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="préalable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Voiture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="est classé" lowerBound="1"
        eType="#//Catégorie"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="est Assigné" eType="#//Réservation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agence">
    <eOperations name="aVoitureDisponible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="demandeVéhicule à autre agence"/>
    <eOperations name="nbVoituresDemandés" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="catégorie" eType="#//Catégorie"/>
    </eOperations>
    <eOperations name="nbVoituresDisponible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="catégorie" eType="#//Catégorie"/>
    </eOperations>
    <eOperations name="transfèreVoiture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="possède" eType="#//Voiture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" upperBound="-1"
        eType="#//Commis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="est dirigé par" lowerBound="1"
        eType="#//Gestionnaire"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreVéhicule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="se trouve" lowerBound="1"
        eType="#//Localisation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commis" eSuperTypes="#//Employé%20Agence">
    <eOperations name="traiteLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gestionnaire" eSuperTypes="#//Employé%20Agence">
    <eOperations name="assigneVéhicule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eOperations name="getPériode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//Voiture"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateDébut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Catégorie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dossier Client">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refère" lowerBound="1"
        eType="#//Client"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contient" upperBound="-1"
        eType="#//Mauvaise_expérience"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contient" upperBound="-1"
        eType="#//Location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Société UE-Rent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="possède Agence" lowerBound="1000"
        upperBound="1000" eType="#//Agence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//Dossier%20Client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mauvaise_expérience"/>
  <eClassifiers xsi:type="ecore:EClass" name="Localisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ville" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employé Agence">
    <eOperations name="assigneVoitureARéservation"/>
  </eClassifiers>
</ecore:EPackage>
